### ISSUE TITLE
Table of contents (structure)

### ISSUE THREAD

**Issue by Nycticorax** [openSUSE/openSUSE-docs-revamped#17]
_The goal of this Issue is to settle on a definitive table of contents (structure) for our docs._
_I first recall the current structure obtained from the outstanding work from Badr, and below I state what structure I would prefer_
_From https://badarotti.github.io/openSUSE-docs-revamped/:_

> ## Pre-Install
> * New user Guide
> * Leap or Tumbleweed?
> * Full, Live or net install?
> * Desktop Environments
> * Full disk install or Dual Boot
> * Disk Partitioning
> * Disk Encryption
> * Snapshots/Btrfs
> * Distros for special uses
> * Getting Help
> ## Install
> * Preparing the Install media
> * Step by step install
> * Quick install guide for the experienced
> ## Orientation
> * The KDE Desktop
> * KDE Settings
> * KDE Resources
> * YaST
> * Snapshot Managment
> * Installing packages
> * Upgrading
> * Backup
> ## After Install Setup
> * Proprietary drivers
> * Printers
> * Scanners
> * Wacom tablet
> * Adding repositories
> * Non-packaged binaries
> * Bluetooth Sound
> * Sharing files
> * Syncing files with other devices
> * Advanced partitioning schemes
> * Wayland vs. xorg
> ## Recommended Setups
> * Internet & social
> * Office users
> * Privacy advocates
> * Graphics designers
> * 3D animators
> * Audio recording
> * Photographers
> * Video editors
> * Education
> * Software developers
> * System administrators
> * Hackers
> * GIS users
> * Home automation
> * Servers/NAS
> * Firewall/Router
> ## Advanced Topics
> * Yast overview
> * Yast vs. Zypper
> * Zypper overview
> * Recovering using Snapper
> * Reporting Bugs
> Contributing to the community
> ## Other Documentation
> * Reference Documentation
> * Wiki
> ## Contribute
> ## Doc Team onboarding
> * Todo
> * Markdown

_To me the presentation is still a bit overwhelming. Not because of the number of items (my list below has more) but because it is too flat, in the sense that in my humble opinion it does provide enough hierarchy to make for a simple and clear browsing experience: the user has to read all the items from the left-hand side panel to find what's needed. Also, I think it could be restructured/reordered to regrou things under common themes._

_I thought of having three levels in the overall on-site presentation. From the user's point of view, the first level is opens a drawer (the uppermost items in the hierarchy below), the second level loads the page (numbered items below), and the third level scrolls up or down on the page (the *-points belows)._ 

_I suggest we have the third-level be represented as a right-hand side navigation menu, see https://github.com/squidfunk/mkdocs-material for a theme and https://code.visualstudio.com/docs/languages/python for a fuller example. Applied to the structure I am presenting below, `Before installing` would open a drawer, `Choosing a distribution` load a page, and `desktop environments` scroll to / select the selected section on the loaded page._

> ## Before installing
> 1. Choosing a distribution
>     * openSUSE distributions
>     * desktop Environments
>     * getting the right installer
>     * FAQ: Issues & solutions
> 2. Installation setups
>     * full disk install
>     * multiple boot
>     * disk partitioning
>     * disk encryption
>     * snapshots/btrfs
> 3. Preparing the installation media
>     * requisites
>     * step by step guide
> ## Installing
> 4. Step by step guide
> 5. Quick install for experienced users
> ## Distro basics
> 6. KDE Plasma basics
>     * X, XWayland & Wayland sessions
>     * settings & keybindings
>     * using panes, bars, widgets & docks
>     * learning more
> 7. GNOME basics
>     * X & Wayland sessions
>     * settings & keybindings
>     * using extensions & plugins
>     * learning more
> 8. Interlude: Fundamental openSUSE concepts
>     * zypper
>     * YaST
>     * snapper & brtfs
>     * the Tumbleweed way
> 9. Getting & installing software
>     * the Leap way & the Tumbleweed way
>     * installing distribution packages
>     * adding repositories
>     * flatpaks
>     * snaps
>     * running with podman
>     * running with libvirt
>     * building from source
> 10. Updating and upgrading
>     * updating packages
>     * upgrading Leap
>     * updating / upgrading Tumbleweed  
> 11. Managing snapshots
>     * brtfs snapshots
>     * rolling back with snapper
>     * introducing `tumbleweed-cli`
>     * tumbleweed snapshots
>     * rolling back with tumbleweed snapshots
> 12. Troubleshooting with autonomy
>     * how Linux logs errors
>     * dmesg & journalctl
>     * finding the culprit
>     * exporting evidence & asking for help
> ## Completing and fine-tuning your setup 
> 13. Finding & installing additional software
>     * codecs
>     * drivers
>     * case study: Intel, NVIDIA and AMD drivers
>     * case study: printers
>     * case study: scanners
>     * case study: touchscreens
>     * case study: Wacom tablets
> 14. Security basics
>     * passwords
>     * gpg & ssh keys
>     * firewall
>     * AppArmor
> 15. Wifi & network
>     * NetworkManager basics
>     * setting up a VPN
> 16. Power management
>     * hibernating from swap
>     * hibernating from file
>     * suspend & lock
>     * CPU power control
> 17. Pairing, syncing, sharing
>     * bluetooth audio
>     * sharing files
>     * syncing files with other devices
> 18. Advanced fine-tunings
>     * kernel parameters
>     * initramfs
>     * systemd basics
> 19. More partitioning
> 20. Recommended setups
>     * internet & social
>     * office users
>     * privacy advocates
>     * graphics designers
>     * 3D animators
>     * audio recording
>     * photographers
>     * video editors
>     * education
>     * software developers
>     * system administrators
>     * hackers
>     * GIS users
>     * home automation
>     * servers/NAS
>     * firewall/Router
> ## Giving back to the community
> 21. Reporting bug reports
>     * the openSUSE bugzilla
>     * the KDE bugilla
>     * GitHub & GitLab Issues
> ## Resources
> 22. Other sources of documentation
>     * Reference documentation
>     * Wiki
> ## Contribute to this docs
> 23. A contributor's checklist
>     * get in touch
>     * open an issue
>     * make a pull request
>     * Doc Team onboarding

_Other things I've changed:_

> ## Before installing (previously named "Pre-Install")
> - moved "dektop environments" from the pre-install section to the "orientation" section, now labelled "Basic routines"
> - added "choose the right installer"
> - changed "dual boot" to "multiple boot" for generality
> ## Installing (previously named "Install")
> - moved "preparing the install media to the "Before installing" section
> ## Distro basics (previous named "Orientation")
> - renamed from "Orientation" as it was a little bit to vague in my opinion
> - restructured all "DE things" to form a homogeneous category
> - added missing basic explanation of the fundamental openSUSE concepts that so many Linux users are unaware of when trying out our distros
> - restructured all other items to balance between common themes and practical associations
> - added missing troubleshooting routines
> ## Completing and fine-tuning your setup (previously named "After Install Setup")
> - merged this section with the previously named "Recommended setups"; also scaled down "Recommended setups" in the hierarchy
> - added missing important elements which were present at https://docs.google.com/document/d/1zERjqqQrWBAoM3B25BIQ4hvTFU_Y7S8L57bh-wb6ld4/edit but didn't make it to the present toc, in particular: case studies for GPUs, codecs, security basics, wifi & network, power management, advanced fine-tunings
> - renamed "Advanced partitioning schemes" to "More partitioning" because to emphasis that we are not talking about alternatives, but about continuations
> - removed "Wayland vs Xorg" and broken them down under the two main DE we're considering in the previous section
> ## Advanced topics (removed)
> - removed because "advanced" is unclear, because its content is not so advanced in my opinion (it's key to build one's comfort zone), or is used elsewhere in the current proposal.
> ## Other Documentation, Contribute, Doc Team oboarding
> - simplified to "Resources" and "Contribute to this docs

_Feel free to argue, identify loopholes or caveats!_

**Comment by daviddyess** [comment]
I am working on the "Zypper Overview" page under "Advanced Topics". I feel it may be beneficial to have a condensed "Zypper Overview" under "Orientation", which would then guide the user to a more in-depth doc under Advanced Topics. I think including some information about Zypper under orientation will help newer users taking the plunge into Tumbleweed.

**Comment by Nycticorax** [comment]
> I am working on the "Zypper Overview" page under "Advanced Topics". I feel it may be beneficial to have a condensed "Zypper Overview" under "Orientation", which would then guide the user to a more in-depth doc under Advanced Topics. I think including some information about Zypper under orientation will help newer users taking the plunge into Tumbleweed.
> 
> Edit: To clarify, I know there is a lot about Zypper on the SDB (Zypper manual alone is 50 pages printed), by more in-depth I just meant a deep outline of Zypper's capability. Explaining command aliases, the types of commands, options, etc.

Heya David, welcome to the party, I too feel we need to talk about `zypper` way before any sort of "advanced topic". In fact in the structure I am proposing above as an amendment to the one we already have, I am tackling zypper things in sections 8, 9 and 10, as I believe that we should put all the cards on the table from the get-go instead of fragmenting information in several disconnected sections. We can have this and still avoid drowning the user under too many details by using the interface -- i.e. collapsable or auto-scrollable subsections inside of sections.

**Comment by daviddyess** [comment]
After thinking about this for a few days, I believe I prefer the proposed structure here. 

The only addition I can think of may go under "Installing", to assist someone not planning to use Gnome, KDE, or Xfce. This would explain Patterns and how to stage the Software portion of installation for a different Desktop Environment.

**Comment by Nycticorax** [comment]
As per minutes https://en.opensuse.org/Opensuse-docs/minutes-meeting-01-06 I will start implementing the new ToC.
