### ISSUE TITLE
Missing version selector from rendered index page

### ISSUE THREAD

**Issue by why-not-try-calmer** [openSUSE/openSUSE-docs-revamped#57]
@hellcp 
Problem: On the picture below, there is no visible list of links acting as a "documentation version selector". 
![Screenshot_20210124_161537](https://user-images.githubusercontent.com/19554213/105634794-22e16400-5e60-11eb-8531-578e80924522.png)
However, the links do exist on the html build, as shown below
![Screenshot_20210124_161807](https://user-images.githubusercontent.com/19554213/105634796-24129100-5e60-11eb-8288-391203ff9119.png)
I am not sure this is a theme-related bug, but if it is, would it be possible to fix it?

**Comment by hellcp** [comment]
This can be closed

**Comment by why-not-try-calmer** [comment]
Indeed!
