### ISSUE TITLE
New page: yast_installer.md

### ISSUE THREAD

**Issue by apinter** [openSUSE/openSUSE-docs-revamped#60]
Opening discussion for #59 
And along that opening with the question: Should we include differences between Leap, Tumbleweed, MicroOS and Kubic - in terms of the installation process - in this document?

**Comment by Nycticorax** [comment]
Ideally there would be one doc for Leap and another for TW, so that the user doesn't have to do the effort of checking for "ifs" and "excepts" and "buts". Lower cognitive load. And it makes it easier to state your assumptions at the outset of the document.

**Comment by Nycticorax** [comment]
Also where should I center the discussion? There are now two places to discuss -- here and the draft PR.

**Comment by apinter** [comment]
Let's center the discussion here, don't like a chatty PR tbh.
