### ISSUE TITLE
Hybrid/Optimus

### ISSUE THREAD

**Issue by why-not-try-calmer** [openSUSE/openSUSE-docs-revamped#77]
split from `install_proprietary.md`.

**Comment by why-not-try-calmer** [comment]
@camckay I had to myself add the new page to the ToC. That's less petting from my cat and more bodyheat for my chair. Not acceptable.  
![Screenshot_20210204_115412](https://user-images.githubusercontent.com/19554213/106883200-f8a16900-66df-11eb-9109-aa89ecc1a831.png)

**Comment by camckay** [comment]
I think this issue should be closed. This document has already been split and merged.
